# Generated by Django 3.0.7 on 2021-02-15 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('stid', models.IntegerField(primary_key=True, serialize=False)),
                ('stname', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MarksModel',
            fields=[
                ('Marksid', models.IntegerField(primary_key=True, serialize=False)),
                ('maths', models.IntegerField()),
                ('physics', models.IntegerField()),
                ('computers', models.IntegerField()),
                ('stid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='n_serializer_app.StudentModel')),
            ],
        ),
    ]
