# Generated by Django 3.0.7 on 2021-02-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0002_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=200)),
                ('c_address', models.TextField()),
                ('c_file', models.FileField(upload_to='')),
                ('c_email', models.EmailField(default=None, max_length=254)),
            ],
        ),
    ]
