# Generated by Django 3.0.7 on 2021-02-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_customer_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='task_list2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_title', models.CharField(max_length=100)),
                ('task_email', models.EmailField(default=None, max_length=254)),
                ('task_number', models.BooleanField()),
            ],
        ),
    ]
